version: '3'

services:
  payload:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URI: postgres://payload:payload@postgres:5432/payload
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      NODE_ENV: production
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: